name: Build-Feature 
run-name: Runner Build-Feature
on:
  # push:
  #   branches: ['feature/*']
  #   paths: ['**/*']
  pull_request:
    branches: ['develop']
    types: ['opened', 'reopened']
    paths: ['**/*']
  # workflow_dispatch:
  #   inputs:
      
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # download code branch source
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with maven
        run: |
          mvn clean test package
          echo "Build with maven!"

